- name: setup Sublime Text repository (1/2)
  shell:
    warn: false
    cmd: |
      curl -O https://download.sublimetext.com/sublimehq-pub.gpg
      pacman-key --add sublimehq-pub.gpg
      pacman-key --init
      pacman-key --lsign-key 8A8F901A
      rm sublimehq-pub.gpg
  changed_when: false

- name: setup Sublime Text repository (2/2)
  ini_file:
    path: /etc/pacman.conf
    mode: '0644'
    section: sublime-text
    option: Server
    value: https://download.sublimetext.com/arch/stable/x86_64

- name: refresh package databases
  command: pacman -Sy
  changed_when: false

- name: install sublime text
  package:
    name: sublime-text