- hosts: localhost
  gather_facts: false
  roles:
    - kewlfft.aur

  tasks:
    - include_tasks: "{{ item }}"
      loop:
        - ./partials/sublime.yaml
        - ./partials/docker.yaml

    - name: install packages
      package:
        name:
          # DEV Tools
          - git
          - go
          - python
          - sed
          - jq
          - vim
          - mysql-workbench
          - kubectl
          - kubectx
          - helm
          - terraform
          - k9s
          # OS Tools
          - keepassxc
          - seahorse
          - gparted
          - htop
          - blueman
          - powertop
          - tilix
          - caffeine-ng
          - redshift
          - oh-my-zsh
          - zsh-autosuggestions
          - zsh-theme-powerlevel10k
          - spotify
          - baobab
          - gnome-disk-utility
          - gparted
          - evince
          - gnome-calendar
          - simple-scan
          - noto-fonts-emoji
          # Chat
          - discord
        state: present

    - name: install AUR custom packages
      become: false
      aur:
        name:
          - slack-desktop
          - teams
          - whatsapp-for-linux
          - drawio-desktop-bin
          - kind-bin
          - lens-bin

    - name: install python packages
      become: false
      pip:
        name:
          - molecule[lint]

    - name: set oh-my-zsh config
      copy:
        src: ../files/.zshrc
        dest: "{{ lookup('env','HOME') }}/.zshrc"
        owner: "{{ lookup('env','USER') }}"
        group: "{{ lookup('env','USER') }}"
        mode: '0644'

  post_tasks:
    - name: set swapiness value
      sysctl:
        name: vm.swappiness
        value: '15'
        state: present